Console.WriteLine("Hello World");
int age = 18;
double price = 9.99;
bool study = true;
char grade = 'A';
string name = "游戏公司";
Console.WriteLine("我今年" + age + "岁");
Console.WriteLine("奶茶的价格是" + price + "元");
Console.WriteLine("正在学习编程：" + study);
Console.WriteLine("我的学习成绩是" + grade);
Console.WriteLine("我的目标公司是" + name);
Console.WriteLine("请输入你的名字");
string yourname = Console.ReadLine();
Console.WriteLine("你好" + yourname);
Console.WriteLine("按任意键退出");
Console.ReadKey();